# Generated by Django 4.2.1 on 2023-06-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_category_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal'},
        ),
    ]
